### PR TITLE
chore(*)move free wrapper into cdefs

### PR DESCRIPTION
**Pull request by chronolaw**
I moved anonymous free functions into `cdefs`,
I think it will make the code more clean and readable.

Does it make sense?

### CODE REVIEW

**Review by fffonion — APPROVED** [review]

**Review by dndx — CHANGES_REQUESTED** [review]
I have some concerns about this change, basically, we create new closures for each `__gc` metamethod to prevent bugs like https://github.com/Kong/atc-router/pull/3 from happening, after this change, it appears that we might introduce the bug back?

Could you test with the example in https://github.com/Kong/atc-router/pull/3 to see if that is the case? I suspect after this change, it will be the same effect as just using `context = ffi_gc(context, clib.context_free)` directly.

**Comment by chronolaw** [comment]
I copied the code of #3 , then run it with this changes, it print out 'ok'. 

Does it means the code works well? or we can test it in kong code base.

**Comment by chronolaw** [comment]
Also, I add some debug code like `print('s free')` `print('r free')` in cdefs.lua wrapper function, 
When I run test code, the output is :

r free
s free
ok

**Comment by chronolaw** [comment]
If we are not sure about this, I think we can merge it after kong 3.0 release.

**Comment by fffonion** [comment]
`cdefs.context_free` is still a closure, thus i feel it should work as expected. @dndx do we want to pursue with this PR (more tests?) or close it?

**Review by dndx — APPROVED** [review]

**Pull request merged**
